### PR TITLE
fixed digit & now truncate to 2 digits

### PR DESCRIPTION
**Pull request by jack-y-xu**

### CODE REVIEW

**Review by asam01 — APPROVED** [review]
is this the only place?

edit: line 175 of Quiz.jsx - can you truncate that as well?

**Review by asam01 — COMMENTED** [review]
add toFixed on line 175 of Quiz.jsx as well

**Review by yukyhaha — APPROVED** [review]

**Comment by yukyhaha** [comment]
can you also add a screenshot here before merging?

**Comment by jack-y-xu** [comment]
image
image

**Pull request merged**
